#!/usr/bin/env racket
#lang racket/base

(require
  racket/string
  racket/function
  command-tree
  (only-in "manager/cascade.rkt" call)
  "manager/container.rkt")

(define dependencies
  '(anaphoric))

(command-tree
  `([install   ,(thunk (install-and-configure-bonny dependencies))]
    [dev       ,(thunk (call "racket ./server.rkt"))]
    [run       ,(thunk (call "/usr/bin/env SITE_MODE=prod racket ./server.rkt"))]
    [dashboard ,(thunk (call "racket ./dashboard/dashboard.rkt"))]
    [test      ,(thunk (call "racket ./tests/test-all.rkt"))]
    ;; bonny commands
    [pirate (install ,create-base-container)
            (create ,clone-container)])
  (current-command-line-arguments))
